functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность пригласить другого игрока
  - Пользователь должен иметь возможность выбрать язык программирования
  - Пользователь должен иметь возможность выбрать уровень сложности
  - Пользователь должен иметь возможность авторизоваться
  - Пользователь должен иметь возможность завершить игру
  - Пользователь должен иметь возможность увидеть результаты игры
  - Пользователь должен иметь возможность играть с ботом
non-functional:
  - требование 3
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - требование 5
  - требование 6
